version: "3"

services:
    app:
      image: fenchelfen/eurostat:frontend
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
#      volumes:
#        - ./src:/app/src
      ports:
        - "3000:3000"

    eurostat:
      image: fenchelfen/eurostat:backend
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - ./app/:/app
      env_file:
        - .env
      depends_on:
        - mysql

    mysql:
      image: fenchelfen/eurostat:database
      build:
        context: .
        dockerfile: ./database/Dockerfile
      volumes:
        - ./docker/mysql/:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      env_file:
        - .env
